### ISSUE TITLE
轮询工具类PollingUtils 方法bug

### ISSUE THREAD

**Issue by showdown-zhou** [xuexiangjys/XUtil#2]
![image](https://user-images.githubusercontent.com/39110520/83231223-bb362480-a1bd-11ea-9b05-eac27ce3b9ac.png)
这个方法不生效`PendingIntent pendingIntent = PendingIntent.getBroadcast(context, 0, intent, PendingIntent.FLAG_NO_CREATE);`应该是`PendingIntent pendingIntent = PendingIntent.getService(context, 0, intent, PendingIntent.FLAG_NO_CREATE);`吧

**Comment by xuexiangjys** [comment]
已解决:
7b202b8752e64bdc5ff36c9ca377bd93fee36c0b
