### ISSUE TITLE
关于XUtil.init

### ISSUE THREAD

**Issue by woaiyuzi** [xuexiangjys/XUtil#5]
## 有如下代码

```java
if (ProcessUtils.isMainProcess()) {
            onMainProcess();
}
```

ps：代码运行一切正常，在主进程中成功返回了`true`，`onMainProcess()`也成功的执行了。  

问题：项目中集成了一个推送框架，需要在`onMainProcess()`中进行注册，成功注册。但是框架内有一个保活服务，会在启动后立马被停止。  

过程：由于框架未打印任何信息，debug过程及其痛苦，在测试到`ProcessUtils.isMainProcess()`时发现如果没有调用该方法，问题就解决了，随即重写了`isMainProcess()`，果然，重写后的方法不会再出问题，查看`ProcessUtils`源码发现需要初始化`XUtil`！！！  

解决：在调用方法前需要，`XUtil.init(this);`  

意见：也不是bug啦，但是由于文档没有提到需要初始化，这种问题又不好一上来就看源码，希望能适当完善一下文档，幸苦了。

**Comment by fuys123** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xuexiangjys** [comment]
框架在provider里面就自动初始化了，没必要写
https://github.com/xuexiangjys/XUtil/blob/7fcb781720b58c777d5c9c8140f6729c9b489aa5/xutil-core/src/main/java/androidx/core/content/FileProvider4Utils.java#L41
